version: 2.1
 
orbs:
  android: circleci/android@0.2.1

commands:
  download-git-lfs-file:
    steps:
      - run:
          name: Download git LFS for circleCI
          command: |
              curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  install-git-lfs-to-ciricle-ci:
    steps:
      - run:
          name: Install git LFS for circleCI
          command: |
              sudo apt-get install git-lfs
      - run:
          name: Initalize git LFS for circleCI
          command: |
            git lfs install

jobs:
  build:
    executor: android/android
    steps:
      - download-git-lfs-file
      - install-git-lfs-to-ciricle-ci
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - run:
          name: Package debug APK
          command: |
            ./gradlew :app:packageDebugUniversalApk --no-daemon
      - store_artifacts:
          path: app/build/outputs/universal_apk/debug
